[build]
builder = "nixpacks"
buildCommand = "dotnet publish cqtrailsclientcore/cqtrailsclientcore.csproj -c Release -o out"

[deploy]
startCommand = "dotnet ./out/cqtrailsclientcore.dll"
healthcheckPath = "/"
healthcheckTimeout = 100 