[build]
builder = "nixpacks"
buildCommand = "dotnet publish cqtrailsclientcore/cqtrailsclientcore.csproj -c Release -o out"

[deploy]
startCommand = "./out/cqtrailsclientcore"
healthcheckPath = "/"
healthcheckTimeout = 100 